# install the libraries

In [27]:
! pip install pandas
! pip install matplotlib 
! pip install 
! pip install numpy

Requirement already satisfied: pandas in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in d:\projects\mumbai_retail_sales_analysis\myenv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

# import the libraries

In [28]:
import pandas as pd
import matplotlib as pyplot
import seaborn as sns
import numpy as np

In [ ]:
import pandas as pd

df = pd.read_csv(r"D:\projects\Mumbai_retail_sales_analysis\Data\Superstore.csv"
,encoding ="latin1")

# encoding lation 1 is used to read the file because it contains special characters that are not supported by the default encoding (utf-8). By specifying encoding="latin1", we can successfully read the file without encountering any errors related to character encoding.

In [15]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## processing the data

In [17]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

# standization of the columns

In [18]:
 # 2. Standardize column names (snake_case is best practice for SQL later)
df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace('-', '_')

# handling dates

In [19]:
 # 3. Handle Dates
print("Parsing dates and handling missing values...")
# Using 'mixed' format as Kaggle CSVs sometimes have inconsistent date formats
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed')
df['ship_date'] = pd.to_datetime(df['ship_date'], format='mixed')

Parsing dates and handling missing values...

In [20]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [22]:
 # 4. Handle Nulls (Drop rows where critical fields like Sales or Dates are missing)
df = df.dropna(subset=['order_date', 'sales', 'category'])

In [25]:
# 5. Localization: Redefining the Geography
print("Applying Mumbai localization mapping...")
    
    # Set static country and state
df['country'] = 'India'
df['state'] = 'Maharashtra'

df.head()

Applying Mumbai localization mapping...

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,India,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,India,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,India,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,India,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,India,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# perform mapping

In [38]:
# FIX: Randomly distribute our exact Mumbai zones across the dataset 
# to completely avoid any 'NaN' or missing region mapping issues.
mumbai_zones = ['Western Suburbs', 'Eastern Suburbs', 'South Mumbai', 'Thane & Navi Mumbai']
df['region'] = np.random.choice(mumbai_zones, size=len(df))

# Map local areas to those specific zones
mumbai_areas = {
    'Western Suburbs': ['Bandra', 'Andheri', 'Borivali', 'Goregaon', 'Malad'],
    'Eastern Suburbs': ['Powai', 'Ghatkopar', 'Kurla', 'Vikhroli', 'Mulund'],
    'South Mumbai': ['Colaba', 'Nariman Point', 'Lower Parel', 'Dadar', 'Worli'],
    'Thane & Navi Mumbai': ['Thane West', 'Vashi', 'Belapur', 'Kalyan', 'Airoli']
}

# Assign city safely based on the newly assigned guaranteed region
df['city'] = df['region'].apply(lambda r: np.random.choice(mumbai_areas[r]))

# Clean up irrelevant columns
if 'postal_code' in df.columns:
    df = df.drop(columns=['postal_code'])

In [39]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,India,Vashi,Maharashtra,Thane & Navi Mumbai,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,India,Kalyan,Maharashtra,Thane & Navi Mumbai,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,India,Kurla,Maharashtra,Eastern Suburbs,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,India,Airoli,Maharashtra,Thane & Navi Mumbai,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,India,Vashi,Maharashtra,Thane & Navi Mumbai,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# STEP 4: Inject Seasonal Authenticity

In [ ]:
# # ==========================================
# # STEP 4: Inject Seasonal Authenticity (optinal )
# # ==========================================
# print("Step 4: Injecting Diwali seasonal trends...")
# # Boost sales by 20% in Oct/Nov to make the data realistic to India
# is_festive_month = df['order_date'].dt.month.isin([10, 11])
# df.loc[is_festive_month, 'sales'] = df.loc[is_festive_month, 'sales'] * 1.20

# # Scale profit proportionally
# profit_margin = df['profit'] / (df['sales'] / 1.20) 
# df.loc[is_festive_month, 'profit'] = df.loc[is_festive_month, 'sales'] * profit_margin

# # Round financial columns
# df['sales'] = df['sales'].round(2)
# df['profit'] = df['profit'].round(2)

Step 4: Injecting Diwali seasonal trends...

# STEP 5: Final Polish & Export

In [ ]:

# ==========================================
# STEP 5: Final Polish & Export
# ==========================================
print("Step 5: Saving the finalized localized dataset...")
output_file = 'Mumbai_Retail_Sales_Data.csv'
df.to_csv(output_file, index=False)

print(f"Done! Dataset successfully saved as '{output_file}'. ")

Step 5: Saving the finalized localized dataset...
Done! Dataset successfully saved as 'Mumbai_Retail_Sales_Data.csv'.

In [42]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,India,Vashi,Maharashtra,Thane & Navi Mumbai,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,314.35,2,0.00,50.30
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,India,Kalyan,Maharashtra,Thane & Navi Mumbai,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",878.33,3,0.00,263.50
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,India,Kurla,Maharashtra,Eastern Suburbs,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,India,Airoli,Maharashtra,Thane & Navi Mumbai,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1149.09,5,0.45,-459.64
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,India,Vashi,Maharashtra,Thane & Navi Mumbai,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,26.84,2,0.20,3.02